// Copyright 2026 David Johnson, G4DPZ, AMSAT-UK
// SPDX-License-Identifier: Apache-2.0

//! Property-based tests for the LTP export session state machine.
//!
//! These tests validate correctness properties of the export session
//! using the `proptest` framework.

use bytes::{Bytes, BytesMut};
use hardy_ltp::segment::{self, CheckpointInfo, ReceptionClaim, Segment};
use hardy_ltp::session::SessionId;
use hardy_ltp::session::export::{ExportAction, ExportConfig, ExportSession};
use proptest::prelude::*;
use std::time::Duration;

// ---------------------------------------------------------------------------
// Property 6: Block Segmentation Reconstructs Original
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    /// **Validates: Requirements 3.1, 3.2**
    ///
    /// Property 6: Block Segmentation Reconstructs Original
    ///
    /// For any block of data and any max_segment_size > 0, segmenting the
    /// block into data segments and concatenating the data payloads in offset
    /// order SHALL produce the original block. The segments SHALL have no gaps
    /// or overlaps, and the final segment SHALL be marked EORP or EOB.
    #[test]
    fn prop_block_segmentation_reconstructs_original(
        block_data in prop::collection::vec(any::<u8>(), 0..=2048),
        max_segment_size in 1usize..=1024,
    ) {
        let block = Bytes::from(block_data.clone());
        let config = ExportConfig {
            max_segment_size,
            max_retransmissions: 5,
            retransmit_timeout: Duration::from_secs(30),
            checkpoint_every_n: 0,
            max_checkpoints: None,
            green: false,
        };

        let session_id = SessionId {
            engine_id: 1,
            session_number: 1,
        };

        let (_session, actions) = ExportSession::new(session_id, block.clone(), 1, config);

        // Extract data segments from SendSegment actions by decoding wire bytes
        let mut data_segments: Vec<(u64, Bytes)> = Vec::new();
        for action in &actions {
            if let ExportAction::SendSegment(wire_bytes) = action {
                let mut reader = &wire_bytes[..];
                let seg = segment::decode(&mut reader)
                    .expect("segment decode should succeed for encoded segment");

                if let Segment::Data { offset, data, .. } = seg {
                    data_segments.push((offset, data));
                }
            }
        }

        // Sort by offset
        data_segments.sort_by_key(|(offset, _)| *offset);

        // Verify no gaps or overlaps: each segment starts where the previous ended
        let mut expected_offset: u64 = 0;
        for (offset, data) in &data_segments {
            prop_assert_eq!(
                *offset, expected_offset,
                "Gap or overlap detected: expected offset {}, got {}",
                expected_offset, offset
            );
            expected_offset += data.len() as u64;
        }

        // Concatenate all payloads
        let mut reconstructed = BytesMut::new();
        for (_, data) in &data_segments {
            reconstructed.extend_from_slice(data);
        }

        // The reconstructed data must equal the original block
        prop_assert_eq!(
            reconstructed.as_ref(),
            block_data.as_slice(),
            "Reconstructed block does not match original"
        );

        // Verify the final segment is marked EORP or EOB
        if let Some(ExportAction::SendSegment(wire_bytes)) = actions.iter().rev().find(|a| matches!(a, ExportAction::SendSegment(_))) {
            let mut reader = &wire_bytes[..];
            let seg = segment::decode(&mut reader)
                .expect("final segment decode should succeed");

            if let Segment::Data { segment_type, .. } = seg {
                prop_assert!(
                    segment_type == hardy_ltp::segment::SegmentType::RedEorp
                        || segment_type == hardy_ltp::segment::SegmentType::RedEob,
                    "Final segment should be EORP or EOB, got {:?}",
                    segment_type
                );
            } else {
                prop_assert!(false, "Expected final SendSegment to be a Data segment");
            }
        } else {
            prop_assert!(false, "No SendSegment actions found");
        }
    }
}

// ---------------------------------------------------------------------------
// Property 7: Export Retransmission Covers Exactly Unclaimed Bytes
// ---------------------------------------------------------------------------

/// Strategy to generate a block and partial claims together.
///
/// Generates a non-empty block (1..=2048 bytes), a max_segment_size > 0,
/// and a set of non-overlapping claimed byte ranges that cover SOME but NOT
/// ALL of the block. The claims are generated by dividing the block into
/// random-sized chunks and randomly selecting a subset as "acknowledged".
fn arb_block_with_partial_claims() -> impl Strategy<Value = (Vec<u8>, usize, Vec<ReceptionClaim>)> {
    (
        prop::collection::vec(any::<u8>(), 2..=2048usize),
        1usize..=512,
    )
        .prop_flat_map(|(block_data, max_segment_size)| {
            let block_len = block_data.len() as u64;
            // Choose a chunk size between 1 and block_len for dividing into claim regions
            let chunk_range = 1u64..=block_len;
            (Just(block_data), Just(max_segment_size), chunk_range)
        })
        .prop_flat_map(|(block_data, max_segment_size, chunk_size)| {
            let block_len = block_data.len() as u64;
            let num_chunks = block_len.div_ceil(chunk_size) as usize;
            // Generate a boolean mask for each chunk (true = acknowledged)
            let mask_strategy = prop::collection::vec(any::<bool>(), num_chunks..=num_chunks);
            (
                Just(block_data),
                Just(max_segment_size),
                Just(chunk_size),
                Just(block_len),
                mask_strategy,
            )
        })
        .prop_filter_map(
            "need at least one claimed and one unclaimed chunk",
            |(block_data, max_segment_size, chunk_size, block_len, mask)| {
                let has_claimed = mask.iter().any(|&b| b);
                let has_unclaimed = mask.iter().any(|&b| !b);
                if !has_claimed || !has_unclaimed {
                    return None;
                }

                let mut claims = Vec::new();
                for (i, &claimed) in mask.iter().enumerate() {
                    if claimed {
                        let offset = i as u64 * chunk_size;
                        let length = chunk_size.min(block_len - offset);
                        claims.push(ReceptionClaim { offset, length });
                    }
                }
                Some((block_data, max_segment_size, claims))
            },
        )
}

/// Computes the expected unclaimed byte ranges given a block length and a set
/// of non-overlapping claims sorted by offset.
fn compute_expected_unclaimed(block_len: u64, claims: &[ReceptionClaim]) -> Vec<(u64, u64)> {
    let mut unclaimed = Vec::new();
    let mut cursor = 0u64;

    for claim in claims {
        if cursor < claim.offset {
            unclaimed.push((cursor, claim.offset));
        }
        cursor = cursor.max(claim.offset + claim.length);
    }
    if cursor < block_len {
        unclaimed.push((cursor, block_len));
    }
    unclaimed
}

/// Merges a sorted list of (start, end) ranges into non-overlapping, non-adjacent ranges.
fn merge_ranges(ranges: &[(u64, u64)]) -> Vec<(u64, u64)> {
    if ranges.is_empty() {
        return Vec::new();
    }

    let mut merged = Vec::new();
    let mut current_start = ranges[0].0;
    let mut current_end = ranges[0].1;

    for &(start, end) in &ranges[1..] {
        if start <= current_end {
            // Overlapping or adjacent — extend
            current_end = current_end.max(end);
        } else {
            // Gap — push current and start new
            merged.push((current_start, current_end));
            current_start = start;
            current_end = end;
        }
    }
    merged.push((current_start, current_end));
    merged
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    /// **Validates: Requirements 3.3, 3.4**
    ///
    /// Property 7: Export Retransmission Covers Exactly Unclaimed Bytes
    ///
    /// For any partially-acknowledged block, the retransmitted segments SHALL
    /// cover exactly the byte ranges NOT claimed within the report window —
    /// no more, no less.
    #[test]
    fn prop_retransmission_covers_exactly_unclaimed_bytes(
        (block_data, max_segment_size, claims) in arb_block_with_partial_claims(),
    ) {
        let block_len = block_data.len() as u64;
        let block = Bytes::from(block_data);
        let config = ExportConfig {
            max_segment_size,
            max_retransmissions: 5,
            retransmit_timeout: Duration::from_secs(30),
            checkpoint_every_n: 0,
            max_checkpoints: None,
            green: false,
        };

        let session_id = SessionId {
            engine_id: 1,
            session_number: 1,
        };

        let (mut session, _initial_actions) =
            ExportSession::new(session_id, block.clone(), 1, config);

        // Compute expected unclaimed ranges from the claims
        let expected_unclaimed = compute_expected_unclaimed(block_len, &claims);

        // Call on_report with the partial claims
        let actions = session.on_report(
            1,              // report_serial
            1,              // checkpoint_serial
            block_len,      // upper_bound
            0,              // lower_bound
            &claims,
        );

        // Extract retransmitted data segments (skip ReportAck actions)
        let mut retransmitted_ranges: Vec<(u64, u64)> = Vec::new();
        for action in &actions {
            if let ExportAction::SendSegment(wire_bytes) = action {
                let mut reader = &wire_bytes[..];
                let seg = segment::decode(&mut reader)
                    .expect("segment decode should succeed");

                if let Segment::Data { offset, data, .. } = seg {
                    retransmitted_ranges.push((offset, offset + data.len() as u64));
                }
            }
        }

        // Sort retransmitted ranges by offset
        retransmitted_ranges.sort_by_key(|(start, _)| *start);

        // Merge adjacent/overlapping retransmitted ranges to get the union
        let merged_retransmitted = merge_ranges(&retransmitted_ranges);

        // Merge expected unclaimed ranges (should already be non-overlapping, but be safe)
        let merged_expected = merge_ranges(&expected_unclaimed);

        // Verify: the union of retransmitted segments covers EXACTLY the unclaimed ranges
        prop_assert_eq!(
            &merged_retransmitted,
            &merged_expected,
            "Retransmitted ranges do not match expected unclaimed ranges.\n\
             Retransmitted: {:?}\n\
             Expected unclaimed: {:?}\n\
             Claims: {:?}\n\
             Block len: {}, max_segment_size: {}",
            merged_retransmitted,
            merged_expected,
            claims,
            block_len,
            max_segment_size,
        );

        // Additional check: no retransmitted byte overlaps with acknowledged ranges
        for &(retx_start, retx_end) in &retransmitted_ranges {
            for claim in &claims {
                let claim_end = claim.offset + claim.length;
                // Check for overlap
                let overlaps = retx_start < claim_end && retx_end > claim.offset;
                prop_assert!(
                    !overlaps,
                    "Retransmitted range ({}, {}) overlaps with acknowledged range ({}, {})",
                    retx_start, retx_end, claim.offset, claim_end,
                );
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Property 15: Intermediate Checkpoint Marking
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    /// **Validates: Requirements 27.2, 27.4**
    ///
    /// Property 15: Intermediate Checkpoint Marking
    ///
    /// For any block with checkpoint_every_n > 0, every Nth segment is a
    /// checkpoint (RedCheckpoint with checkpoint info) UNLESS it's the final
    /// segment. The final segment is ALWAYS RedEob (type 3) with checkpoint
    /// info. Non-checkpoint, non-final segments are RedData (type 0) with no
    /// checkpoint info. All checkpoint serial numbers are strictly increasing.
    #[test]
    fn prop_intermediate_checkpoint_marking(
        block_data in prop::collection::vec(any::<u8>(), 1..=4096usize),
        max_segment_size in 1usize..=512,
        checkpoint_every_n in 1u32..=10,
    ) {
        let block = Bytes::from(block_data);
        let config = ExportConfig {
            max_segment_size,
            max_retransmissions: 5,
            retransmit_timeout: Duration::from_secs(30),
            checkpoint_every_n,
            max_checkpoints: None,
            green: false,
        };

        let session_id = SessionId {
            engine_id: 1,
            session_number: 1,
        };

        let (_session, actions) = ExportSession::new(session_id, block, 1, config);

        // Decode all SendSegment actions to get data segments in order
        let mut segments: Vec<(segment::SegmentType, Option<CheckpointInfo>)> = Vec::new();
        for action in &actions {
            if let ExportAction::SendSegment(wire_bytes) = action {
                let mut reader = &wire_bytes[..];
                let seg = segment::decode(&mut reader)
                    .expect("segment decode should succeed");

                if let Segment::Data { segment_type, checkpoint, .. } = seg {
                    segments.push((segment_type, checkpoint));
                }
            }
        }

        // Must have at least one segment
        prop_assert!(!segments.is_empty(), "Expected at least one data segment");

        let num_segments = segments.len();
        let mut checkpoint_serials: Vec<u64> = Vec::new();

        for (idx, (seg_type, checkpoint)) in segments.iter().enumerate() {
            let segment_number = idx + 1; // 1-indexed
            let is_last = idx == num_segments - 1;

            if is_last {
                // (b) The final segment is ALWAYS RedEob (type 3) with checkpoint info
                prop_assert_eq!(
                    *seg_type,
                    segment::SegmentType::RedEob,
                    "Final segment (index {}) should be RedEob, got {:?}",
                    idx, seg_type
                );
                prop_assert!(
                    checkpoint.is_some(),
                    "Final segment (index {}) should have checkpoint info",
                    idx
                );
                if let Some(ckpt) = checkpoint {
                    checkpoint_serials.push(ckpt.serial);
                }
            } else if segment_number % (checkpoint_every_n as usize) == 0 {
                // (a) Every Nth segment (1-indexed) is a checkpoint (RedCheckpoint)
                prop_assert_eq!(
                    *seg_type,
                    segment::SegmentType::RedCheckpoint,
                    "Segment {} (index {}) should be RedCheckpoint (every {}th), got {:?}",
                    segment_number, idx, checkpoint_every_n, seg_type
                );
                prop_assert!(
                    checkpoint.is_some(),
                    "Checkpoint segment {} (index {}) should have checkpoint info",
                    segment_number, idx
                );
                if let Some(ckpt) = checkpoint {
                    checkpoint_serials.push(ckpt.serial);
                }
            } else {
                // (c) Non-checkpoint, non-final segments are RedData with no checkpoint info
                prop_assert_eq!(
                    *seg_type,
                    segment::SegmentType::RedData,
                    "Segment {} (index {}) should be RedData, got {:?}",
                    segment_number, idx, seg_type
                );
                prop_assert!(
                    checkpoint.is_none(),
                    "Non-checkpoint segment {} (index {}) should not have checkpoint info",
                    segment_number, idx
                );
            }
        }

        // (d) All checkpoint serial numbers are present and strictly increasing
        for i in 1..checkpoint_serials.len() {
            prop_assert!(
                checkpoint_serials[i] > checkpoint_serials[i - 1],
                "Checkpoint serial {} (at index {}) is not strictly greater than {} (at index {}). All serials: {:?}",
                checkpoint_serials[i], i, checkpoint_serials[i - 1], i - 1, checkpoint_serials
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Feature: tvr-ltp-integration, Property 4: Suspend-Then-Resume Preserves Timer Remaining Duration
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    /// **Validates: Requirements 2.2, 3.1, 3.2, 3.3, 3.4**
    ///
    /// Property 4: Suspend-Then-Resume Preserves Timer Remaining Duration
    ///
    /// For any timer with remaining duration `d` at the moment of suspension,
    /// resuming that timer shall schedule a new deadline at `now + d`,
    /// preserving the exact remaining duration that was recorded during
    /// suspension.
    #[test]
    fn prop_suspend_then_resume_preserves_remaining_duration(
        block_data in prop::collection::vec(any::<u8>(), 1..=2048usize),
        max_segment_size in 1usize..=512,
        checkpoint_every_n in 0u32..=5,
        remaining_millis in prop::collection::vec(1u64..=600_000, 1..=64),
    ) {
        let block = Bytes::from(block_data);
        let config = ExportConfig {
            max_segment_size,
            max_retransmissions: 5,
            retransmit_timeout: Duration::from_secs(30),
            checkpoint_every_n,
            max_checkpoints: None,
            green: false,
        };

        let session_id = SessionId {
            engine_id: 1,
            session_number: 42,
        };

        let (mut session, _initial_actions) =
            ExportSession::new(session_id, block, 1, config);

        // Step 1: Suspend timers — get the list of checkpoint serials with active timers
        let suspend_actions = session.suspend_timers();

        // Collect the checkpoint serials that were suspended
        let suspended_serials: Vec<u64> = suspend_actions
            .iter()
            .filter_map(|a| {
                if let ExportAction::SuspendTimer { checkpoint_serial } = a {
                    Some(*checkpoint_serial)
                } else {
                    None
                }
            })
            .collect();

        // After suspend, timers_suspended() must be true
        prop_assert!(
            session.timers_suspended(),
            "timers_suspended() should be true after suspend_timers()"
        );

        // If there are no active timers (e.g., empty block edge case), skip the resume check
        if suspended_serials.is_empty() {
            return Ok(());
        }

        // Step 2: Generate random remaining durations for each suspended timer.
        // Use the generated remaining_millis, cycling if needed.
        let suspended_with_durations: Vec<(u64, Duration)> = suspended_serials
            .iter()
            .enumerate()
            .map(|(i, &serial)| {
                let millis = remaining_millis[i % remaining_millis.len()];
                (serial, Duration::from_millis(millis))
            })
            .collect();

        // Step 3: Resume timers with those durations
        let resume_actions = session.resume_timers(&suspended_with_durations);

        // Step 4: Assert that the returned ResumeTimer actions contain exactly
        // the same checkpoint serials and durations that were passed in
        let resumed: Vec<(u64, Duration)> = resume_actions
            .iter()
            .filter_map(|a| {
                if let ExportAction::ResumeTimer {
                    checkpoint_serial,
                    remaining,
                } = a
                {
                    Some((*checkpoint_serial, *remaining))
                } else {
                    None
                }
            })
            .collect();

        prop_assert_eq!(
            resumed.len(),
            suspended_with_durations.len(),
            "Number of resumed timers ({}) should equal number of suspended timers ({})",
            resumed.len(),
            suspended_with_durations.len(),
        );

        // Verify each resumed timer matches the input exactly
        for (expected, actual) in suspended_with_durations.iter().zip(resumed.iter()) {
            prop_assert_eq!(
                actual.0,
                expected.0,
                "Resumed checkpoint serial {} does not match expected {}",
                actual.0,
                expected.0,
            );
            prop_assert_eq!(
                actual.1,
                expected.1,
                "Resumed duration {:?} does not match expected {:?} for checkpoint serial {}",
                actual.1,
                expected.1,
                expected.0,
            );
        }

        // Step 5: After resume, timers_suspended() must be false
        prop_assert!(
            !session.timers_suspended(),
            "timers_suspended() should be false after resume_timers()"
        );
    }
}

// ---------------------------------------------------------------------------
// Helper: extract checkpoint serial numbers from a list of ExportActions
// ---------------------------------------------------------------------------

/// Decodes all SendSegment actions and returns checkpoint serial numbers
/// in the order they appear.
fn extract_checkpoint_serials(actions: &[ExportAction]) -> Vec<u64> {
    let mut serials = Vec::new();
    for action in actions {
        if let ExportAction::SendSegment(wire_bytes) = action {
            let mut reader = &wire_bytes[..];
            if let Ok(Segment::Data {
                checkpoint: Some(CheckpointInfo { serial, .. }),
                ..
            }) = segment::decode(&mut reader)
            {
                serials.push(serial);
            }
        }
    }
    serials
}

// ---------------------------------------------------------------------------
// Property 8: Checkpoint Serial Numbers Strictly Increase
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    /// **Validates: Requirements 3.8**
    ///
    /// Property 8: Checkpoint Serial Numbers Strictly Increase
    ///
    /// For any export session across all checkpoints sent (initial and
    /// retransmissions), each successive checkpoint serial number SHALL be
    /// strictly greater than all previously used checkpoint serial numbers
    /// in that session.
    #[test]
    fn prop_checkpoint_serials_strictly_increase(
        block_data in prop::collection::vec(any::<u8>(), 1..=2048usize),
        max_segment_size in 1usize..=512,
        checkpoint_every_n in 0u32..=5,
    ) {
        let block = Bytes::from(block_data.clone());
        let block_len = block.len();
        let config = ExportConfig {
            max_segment_size,
            max_retransmissions: 5,
            retransmit_timeout: Duration::from_secs(30),
            checkpoint_every_n,
            max_checkpoints: None,
            green: false,
        };

        let session_id = SessionId {
            engine_id: 1,
            session_number: 1,
        };

        // Create session and collect initial checkpoint serials
        let (mut session, initial_actions) =
            ExportSession::new(session_id, block, 1, config);

        let mut all_serials = extract_checkpoint_serials(&initial_actions);

        // Simulate a partial report: acknowledge only the first half of the block.
        // This should trigger retransmission of the unclaimed second half with
        // a new checkpoint serial number.
        let half = (block_len / 2).max(1) as u64;
        if half < block_len as u64 {
            let claims = vec![ReceptionClaim {
                offset: 0,
                length: half,
            }];
            let retransmit_actions =
                session.on_report(1, 1, block_len as u64, 0, &claims);
            let retransmit_serials = extract_checkpoint_serials(&retransmit_actions);
            all_serials.extend(retransmit_serials);
        }

        // Verify strict monotonicity: each serial must be greater than all
        // previous serials.
        for i in 1..all_serials.len() {
            prop_assert!(
                all_serials[i] > all_serials[i - 1],
                "Checkpoint serial {} (at index {}) is not strictly greater than {} (at index {}). All serials: {:?}",
                all_serials[i], i, all_serials[i - 1], i - 1, all_serials
            );
        }

        // Additionally verify that all serials are unique (implied by strict
        // increase, but let's be explicit).
        let mut sorted = all_serials.clone();
        sorted.sort();
        sorted.dedup();
        prop_assert_eq!(
            sorted.len(),
            all_serials.len(),
            "Duplicate checkpoint serial numbers found: {:?}",
            all_serials
        );
    }
}
